### ISSUE TITLE
Provide a means for supplying a validator

### ISSUE THREAD

**Issue by talios** [derive4j/derive4j#41]
I was thinking it would be handy to have some means of providing a validator over the ADT values, I often use this feature of Immutables and keep thinking it would be useful here.

Currently, derive4j checks for nullness in its created instances, but it would be nice if we could define something like:

```java
protected|public void validate() {
  this.match(....)
}
```

or

```java
protected|public static Predicate<MyAdtType> validator = it -> ....;
```

which if existed, gets called before returning the constructed value.

Thoughts?

**Comment by jbgi** [comment]
I think smart constructors can do what you want (using visibility = Smart). eg. https://github.com/jbgi/Softshake2015Demo/blob/70c23ac39640ef678361c9066d37373dfff1f712/src/main/java/com/github/jbgi/softshake/domain/model/PersonName.java#L85

Would that style suit your needs?

**Comment by talios** [comment]
Hard to tell, since whenever I add an `@Derive` I get errors about a missing `make` attribute, even if I specify it ( using 0.8.2 ).

Without seeing that that generates hard to say, the problem I have with smart constructors on the abstract class, is then you've got two locations for dealing with things - the pluralized class with get/mod methods etc, and the abstract with constructors.

**Comment by jbgi** [comment]
@talios about the error: could it be because you depends on an older version of the `derive4j-annotation` artifact? if that is not the problem could you point me to a project or sample test-case that exhibit the problem?

as for validation. I see that generating the validation code would be nice indeed. However, unlike with null, I want them to be safe: generated smart constructors would return something like `Validation<E, Adt>`. I think it is doable at least for product types. For sum types I am not sure, because one may want to make some constructors 'smart' but not some others. To simplify the API, all constructors of a sum type that take parameters would be smart. Value constructors (without parameters) would be normal ones.

The validation code would be taken from an static instance of the visitor of the ADT that return either a`Boolean`, an optional error value, or a list of errors.

**Comment by talios** [comment]
This is the project: https://github.com/HalBuilder/halbuilder-core and https://github.com/HalBuilder/halbuilder-core/blob/develop/src/main/java/com/theoryinpractise/halbuilder5/Rel.java is the derive4j class.

**Comment by jbgi** [comment]
@talios using the following works for me:
```java
@Data(value = @Derive(withVisibility = Visibility.Smart),
      flavour = Flavour.Javaslang, arguments = ArgOption.checkedNotNull)
```
What `Smart` visibility does is that it makes all constructor and setter/modifier methods package private.

**Comment by jbgi** [comment]
closing in favor of #44
