### ISSUE TITLE
Add Guava flavor

### ISSUE THREAD

**Issue by h908714124** [derive4j/derive4j#46]
for projects stuck on Java 7

**Comment by jbgi** [comment]
I personally use [fugue](https://bitbucket.org/atlassian/fugue) 2(.6.1) for java 6/7 projects because of they have a better `Option` type and also an `Either`.

But, yeah, I will add a Guava flavor for the next release. Or If you want, I will gladly accept a PR. There is two classes to modify:
- https://github.com/derive4j/derive4j/blob/master/annotation/src/main/java/org/derive4j/Flavour.java
- https://github.com/derive4j/derive4j/blob/master/processor/src/main/java/org/derive4j/processor/derivator/FlavourImpl.java

**Comment by jbgi** [comment]
Fixed by eb067d825282c1ec94e3980edd9e685e8a5692d8

**Comment by jbgi** [comment]
@h908714124: 0.9 has been released with your commit!
