### ISSUE TITLE
More descriptive name than `@Data`

### ISSUE THREAD

**Issue by binkley** [derive4j/derive4j#52]
What a nice processor!

I would ask you use a more descriptive name than `@Data` for annotation:

1. "Data" is such a generic word, difficult to scan code with `@Data` and grok something interesting is happening.
2. "Data" may clash with user code or other packages which also have a `Data` class, especially after imports.
3. In particular, Lombok is probably the most popular 3rd-party annotation processor, and it, too, has a `Data` class, which does something rather different.
4. This package is version 0.9.1 (as of when I wrote this), so you should have some freedom in refactoring before hitting the magic 1.0.0 and your public API is frozen (assuming semantic versioning).

You have many fine alternative choices for naming the annotation.  First to my mind is `@ADT`.  A web search on "ADT" turns up near the top the right Wikipedia page to understand some background on this library's goals.

Cheers,
--binkley

**Comment by jbgi** [comment]
Thanks for the feedback! `@Data` was chosen to mimic Haskell declaration of algebraic data types. It is probably enough reference for project like [highj](/highj/highj) but probably not for less FP focused teams/projects.
So I agree the annotation could be more explicit to ease research on the underlying concepts. `@AlgebraicDataType` could do fine, I think. (?)

I will wait for more library users feedbacks/suggestions before deprecating `@Data`. (cc @clinuxrulz, @talios, @gneuvill, @rdegnan, @h908714124  )

**Comment by talios** [comment]
Name classes are always going to happen, which is why we have `package`s in Java. Personally, I'm not sure where clashes would actually occur, `@Data` usually appears in a standalone interface/abstract class ( unless you're doing inner classes for a specific reason ), which stands separate from ADT4j, Immutables, or Lombok classes.

It's not something that appears in run-time dependencies, or user code ( unless you're writing your own processor/extension ) so I'm not sure it really matters.

`@AlbgebraicDataType` feels a bit toooooo wordy, even if accurate. Maybe explore the "annotation of annotations" approach, where I could have my own annotation, to which I add preferred styling/setup/config I always use.

Then, `@AlbgebraicDataType` could just implement that, and be a `@Data`, no real need to deprecate I don't think?

**Comment by clinuxrulz** [comment]
```@Data``` seems fine to me. As we are making a **data**-type. But I would be quite happy with ```@ADT``` too.

**Comment by binkley** [comment]
Thanks for the useful comments.  My concern is less with Lombok (more an issue of confusion between `@Data` and `@Data` in a large codebase, the meaning dependent on imports) and with user classes named `Data` which is (sadly) common in some of the client code I improve.  Obviously the compiler would not be confused.

In such cases priority would be given to the local codebase's import of `Data`, so the annotation would be used as `@org.derive4j.Data`.  Again the compiler won't care, but human readers will find this contra typical coding standards which prefer imported short names when possible.

**Comment by gneuvill** [comment]
I'd keep `@Data` and can see no reason for it to be used _in the same file_ along with `lombok.Data` (which denotes a **mutable** type...). If an alias is still desired, I'd vote for `@data` to mimic Haskell even more.

**Comment by jbgi** [comment]
The next release will allow the usage of user defined annotation instead of `@Data`. See #56. (following @talios suggestion)

**Comment by binkley** [comment]
Thank you!  This addresses my concerns.  Looking forward to #56.
